plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version "${moddevgradle_version}"
    id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "2.+"
}

version = "mc${archive_minecraft_version}-NeoForge-${mod_version}"
group = project.maven_group
var realVersion = project.mod_version + '+neoforge'

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url "https://maven.neoforged.net/releases" }
    maven { url "https://maven.su5ed.dev/releases" }
    maven {
        name = "BlameJared"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of the maven that hosts JEI files
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }
    maven { url "https://maven.terraformersmc.com/" }
    maven {
        // Shedaniel's maven (Architectury API)
        url = "https://maven.architectury.dev"
        content {
            includeGroup "dev.architectury"
        }
    }
    maven {
        url = "https://mvn.devos.one/snapshots/"
    }
    maven {
        // saps.dev Maven (KubeJS and Rhino)
        url = "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
            includeGroup "dev.latvian.apps"
        }
    }
    maven {
        // For com.github.rtyley:animated-gif-lib-for-java, a KubeJS dependency
        url 'https://jitpack.io'
        content {
            includeGroup "com.github.rtyley"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    flatDir { dir 'libs' }
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            ideName = "Run ${project.mod_id} - Client"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            systemProperty 'mixin.debug.export', 'true'
            systemProperty 'mixin.debug.verbose', 'true'
        }

        server {
            server()
            ideName = "Run ${project.mod_id} - Server"
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            systemProperty 'mixin.debug.export', 'true'
            systemProperty 'mixin.debug.verbose', 'true'
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()
            ideName = "Run ${project.mod_id} - Data"
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "org.sinytra.forgified-fabric-api:forgified-fabric-api:${project.fabric_version}"
    jarJar "org.sinytra.forgified-fabric-api:fabric-api-base:2.0.3+b11575294c"
    jarJar "org.sinytra.forgified-fabric-api:fabric-transfer-api-v1:8.0.6+7b5559184c"
    jarJar "org.sinytra.forgified-fabric-api:fabric-api-lookup-api-v1:2.0.12+29e133704c"
    jarJar "org.sinytra.forgified-fabric-api:fabric-rendering-fluids-v1:6.0.1+a22884974c"
    jarJar "org.sinytra.forgified-fabric-api:fabric-lifecycle-events-v1:4.1.1+150d8dbd4c"
    jarJar "org.sinytra.forgified-fabric-api:fabric-recipe-api-v1:9.0.16+d86288d44c"
    jarJar "org.sinytra:forgified-fabric-loader:2.5.83+0.19.3+26.1.2"
    jarJar "org.sinytra.forgified-fabric-api:fabric-events-interaction-v0:5.2.2+9abcb0834c"

    implementation "dev.architectury:architectury-neoforge:${project.architectury_version}"
    implementation "maven.modrinth:cloth-config:${project.cloth_config_version}+neoforge"
    implementation "maven.modrinth:kiwi:${project.kiwi_version}+neoforge"
    annotationProcessor "maven.modrinth:kiwi:${project.kiwi_version}+neoforge"

    implementation "maven.modrinth:jade:${project.jade_version}+neoforge"
    implementation "me.shedaniel:RoughlyEnoughItems-neoforge:${project.rei_version}"
    compileOnly "me.shedaniel:REIPluginCompatibilities-forge-annotations:12.+"

    implementation "mezz.jei:jei-${project.jei_minecraft_version}-common-api:${project.jei_version}"
    implementation "mezz.jei:jei-${project.jei_minecraft_version}-neoforge-api:${project.jei_version}"
    implementation "mezz.jei:jei-${project.jei_minecraft_version}-neoforge:${project.jei_version}"
    implementation "dev.latvian.mods:kubejs-neoforge:${kubejs_version}"
    implementation "dev.latvian.mods:better-advanced-tooltips:2601.1.0-build.9"

    implementation fileTree(dir: "libs", include: ["*.jar"])
    annotationProcessor fileTree(dir: "libs", include: ["*.jar"])

    implementation 'com.google.errorprone:error_prone_annotations:2.36.0'
}

processResources {
    inputs.property "version", realVersion
    inputs.property "neo_version_range", project.neo_version_range
    inputs.property "minecraft_version_range", project.minecraft_version_range

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "file": ["jarVersion": realVersion],
                "neo_version_range": project.neo_version_range,
                "minecraft_version_range": project.minecraft_version_range
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
//    it.options.compilerArgs.add("-Akiwi.clientOnlyMod")
}

java {
//    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude("/assets/${project.mod_id}/lang/en_us.existing.json")
    exclude("/data/${project.mod_id}/lychee_fragment")
    exclude("/data/${project.mod_id}/predicate")
    exclude("/data/${project.mod_id}/recipe")
//    exclude("/snownee/${project.mod_id}/datagen/LycheeDataGen.class")
    exclude("/snownee/${project.mod_id}/datagen/TestRecipeProvider.class")

    exclude '**/*.py'
    exclude '**/*.zip'
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

publishMods {
    file = jar.archiveFile
    changelog = file('CHANGELOG.md').exists() ? file('CHANGELOG.md').text : ''
    type = ['release': STABLE, 'beta': BETA, 'alpha': ALPHA][release_type]
    modLoaders.add("neoforge")
    displayName = "[NeoForge ${supported_version}] ${mod_version}"
    version = realVersion

    curseforge {
        projectId = "567403"
        client = true
        server = true
        accessToken = providers.environmentVariable("CURSE_TOKEN")
        minecraftVersions.add(minecraft_version)
        minecraftVersions.add("26.1")
        minecraftVersions.add("26.1.1")
        requires("kiwi")
        optional("cloth-config")
    }
    modrinth {
        projectId = "TdN6LxjM"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
        minecraftVersions.add("26.1")
        minecraftVersions.add("26.1.1")
        requires("kiwi")
        optional("cloth-config")
    }
}