plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
    id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "2.+"
}

version = project.minecraft_version + "-Fabric-" + project.mod_version
group = project.maven_group
var realVersion = project.mod_version + '+fabric'

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        // location of the maven that hosts JEI files
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven { url = "https://maven.parchmentmc.org" }
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }
    maven { url "https://maven.terraformersmc.com/" }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = "https://mvn.devos.one/snapshots/"
    }
    maven { url = "https://api.modrinth.com/maven" }
    maven {
        // saps.dev Maven (KubeJS and Rhino)
        url = "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
            includeGroup "dev.latvian.apps"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    flatDir { dir 'libs' }
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}

// Include resources generated by data generators.
sourceSets {
    main.resources.srcDirs += "src/generated/resources"
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.20.6:${project.parchmentmc_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // PSA: Some older mods, compiled on Loom 0.2.1, might have outdated Maven POMs.
    // You may need to force-disable transitiveness on them.
//    modImplementation("dev.architectury:architectury-fabric:${project.architectury_version}")
//    modApi("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {
//        exclude(group: "net.fabricmc.fabric-api")
//    }
    modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"

    modImplementation "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
//
    modCompileOnlyApi("mezz.jei:jei-${project.minecraft_version}-common-api:${project.jei_version}")
    modCompileOnlyApi("mezz.jei:jei-${project.minecraft_version}-fabric-api:${project.jei_version}")
    modImplementation("mezz.jei:jei-${project.minecraft_version}-fabric:${project.jei_version}")

    modImplementation annotationProcessor("maven.modrinth:kiwi:${project.kiwi_version}+fabric")

    implementation 'com.google.errorprone:error_prone_annotations:2.36.0'

    compileOnly "dev.latvian.mods:kubejs-neoforge:${kubejs_version}"

modImplementation "maven.modrinth:jade:${project.jade_version}+fabric"

//    modCompileOnly "dev.emi:emi-fabric:${emi_version}:api"
    modImplementation "dev.emi:emi-fabric:${emi_version}"

    compileOnly "maven.modrinth:spectrum:1.10.5-1.21.1-fabric"
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude("/assets/${project.mod_id}/lang/en_us.existing.json")
    exclude("/data/${project.mod_id}/lychee_fragment")
    exclude("/data/${project.mod_id}/predicate")
    exclude("/data/${project.mod_id}/recipe")
    exclude("/snownee/${project.mod_id}/datagen/LycheeDataGen.class")
    exclude("/snownee/${project.mod_id}/datagen/TestRecipeProvider.class")

    exclude '**/*.py'
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

configurations.configureEach {
    resolutionStrategy {
        force "dev.architectury:architectury-fabric:${project.architectury_version}"
    }
}

publishMods {
    file = remapJar.archiveFile
    changelog = file('CHANGELOG.md').exists() ? file('CHANGELOG.md').text : ''
    type = ['release': STABLE, 'beta': BETA, 'alpha': ALPHA][release_type]
    modLoaders.add("fabric")
    modLoaders.add("quilt")
    displayName = "[Fabric ${supported_version}] ${mod_version}"
    version = realVersion

    curseforge {
        projectId = "574650"
        client = true
        server = true
        accessToken = providers.environmentVariable("CURSE_TOKEN")
        minecraftVersions.add(minecraft_version)
        requires("kiwi-fabric")
        optional("cloth-config")
    }
    modrinth {
        projectId = "TdN6LxjM"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
        requires("kiwi")
        optional("cloth-config")
    }
}