org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=true
# org.gradle.java.home=D:/Program Files/Eclipse Foundation/jdk-17.0.1.12-hotspot
# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.1
supported_version=1.21.1
loader_version=0.16.10
# Mod Properties
mod_version=6.7.0
release_type=beta
mod_id=lychee
maven_group=snownee.lychee
archives_base_name=Lychee
# Dependencies
# https://fabricmc.net/develop/
fabric_version=0.115.2+1.21.1
# https://modrinth.com/mod/cloth-config/versions
cloth_config_version=15.0.140
# https://modrinth.com/mod/modmenu/versions
modmenu_version=11.0.3
# https://modrinth.com/mod/architectury-api/versions
architectury_version=13.0.3
# https://modrinth.com/mod/kiwi/versions
kiwi_version=15.8.2
# https://modrinth.com/mod/rei/versions
rei_version=16.0.799
# https://modrinth.com/mod/jei/versions
jei_version=19.27.0.340
wthitVersion=12.2.1
milk_lib_version=1.3.61
kubejs_version=2101.7.1-build.181
rhino_version=2001.2.2-build.6
parchmentmc_version=2024.06.16
# https://modrinth.com/mod/jade/versions
jade_version=15.10.2
# https://modrinth.com/mod/emi/versions
emi_version=1.1.22+1.21.1