org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=true
# Minecraft / Loader Properties
minecraft_version=26.1.2
archive_minecraft_version=26.1
supported_version=26.1.X
moddevgradle_version=2.0.141
# https://github.com/Sinytra/ForgifiedFabricAPI/blob/26.1.2/ffapi.gradle.properties
neo_version=26.1.2.95
neo_version_range=[26.1.2,)
minecraft_version_range=[26.1.2,26.2)

# Mod Properties
mod_version=26.0.5
release_type=release
mod_id=lychee
maven_group=snownee.lychee
archives_base_name=Lychee
# Dependencies
# https://github.com/Sinytra/ForgifiedFabricAPI
# https://modrinth.com/mod/forgified-fabric-api/versions
fabric_version=0.155.2+26.1.2+3.5.3
# https://modrinth.com/mod/cloth-config/versions
cloth_config_version=26.1.154
# https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-beta.1
# https://modrinth.com/mod/architectury-api/versions
architectury_version=20.0.7
# https://modrinth.com/mod/kiwi/versions
kiwi_version=26.0.16
# https://modrinth.com/mod/rei/versions
rei_version=26.1.819
# https://modrinth.com/mod/jei/versions
# https://maven.blamejared.com/mezz/jei/
jei_version=29.12.0.40
jei_minecraft_version=26.1.2
wthitVersion=12.2.1
milk_lib_version=1.3.61
# https://modrinth.com/mod/kubejs/versions
kubejs_version=26.1.2-8.0.4
# https://modrinth.com/mod/jade/versions
jade_version=26.1.8
# https://modrinth.com/mod/emi/versions
emi_version=1.1.22+1.21.1