modLoader="javafml"
loaderVersion="*"
license="ARR"

[[mods]]
modId="lychee"
version="${file.jarVersion}"
displayName="Lychee Tweaker"
authors="Snownee"
credits="SettingDust, MikhailTapio"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lychee-fabric"
issueTrackerURL="https://github.com/Snownee/Lychee/issues"
description="Data-driven in-world crafting"
logoFile="assets/lychee/logo.png"

[[mixins]]
config="lychee.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.lychee]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"

[[dependencies.lychee]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"

[[dependencies.lychee]]
modId="kiwi"
type="required"
versionRange="[26,)"

[[dependencies.lychee]]
modId="cloth_config"
type="optional"
versionRange="[26.1.154,)"

[[dependencies.lychee]]
modId="jei"
type="optional"
versionRange="[29.12.0.40,)"

[[dependencies.lychee]]
modId="roughlyenoughitems"
type="optional"
versionRange="[26.1.819,)"

[[dependencies.lychee]]
modId="jade"
type="optional"
versionRange="[26.1.8,)"

[[dependencies.lychee]]
modId="kubejs"
type="optional"
versionRange="[26.1.2-8.0.3,)"
